"""Model for Booking

Revision ID: 09d3f941c441
Revises: bba0551572eb
Create Date: 2025-08-01 13:59:07.530504

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '09d3f941c441'
down_revision = 'bba0551572eb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('seats_booked', sa.Integer(), nullable=False))
    op.add_column('bookings', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('bookings', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('bookings', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.drop_column('bookings', 'seat_number')
    op.drop_column('bookings', 'booking_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('booking_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('bookings', sa.Column('seat_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('bookings', 'is_deleted')
    op.drop_column('bookings', 'updated_at')
    op.drop_column('bookings', 'created_at')
    op.drop_column('bookings', 'seats_booked')
    # ### end Alembic commands ###