"""Model for Booking

Revision ID: 0cebb3013276
Revises: 06882d6e8414
Create Date: 2025-08-01 11:05:42.784970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cebb3013276'
down_revision = '06882d6e8414'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trains', sa.Column('source', sa.String(), nullable=False))
    op.add_column('trains', sa.Column('destination', sa.String(), nullable=False))
    op.add_column('trains', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('trains', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'trains', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'trains', type_='unique')
    op.drop_column('trains', 'updated_at')
    op.drop_column('trains', 'created_at')
    op.drop_column('trains', 'destination')
    op.drop_column('trains', 'source')
    # ### end Alembic commands ###