"""Model for Booking

Revision ID: 97cee8c4029d
Revises: 09d3f941c441
Create Date: 2025-08-01 17:57:33.659711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97cee8c4029d'
down_revision = '09d3f941c441'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('is_tatkal', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'is_tatkal')
    # ### end Alembic commands ###