"""Model for Booking

Revision ID: bba0551572eb
Revises: 84ee84a17700
Create Date: 2025-08-01 11:26:14.408988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bba0551572eb'
down_revision = '84ee84a17700'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'bookings', ['id'])
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_verified')
    op.drop_constraint(None, 'bookings', type_='unique')
    # ### end Alembic commands ###